// This is used to avoid CLS (Cumulative Laushout Shift) during initial page render.
// This is dummy data pulled from the database, but will align the leaderboard tables.
export const preloadData = [
    {
        place: 1,
        username: 'Evan',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 2,
        username: 'fruloo',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 3,
        username: 'thlurp',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 4,
        username: 'Gliss',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 5,
        username: 'Bandi',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 6,
        username: 'Deadoom',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 7,
        username: 'mrbrownies',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 8,
        username: 'jex',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 9,
        username: 'RedJaw',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 10,
        username: 'Juggernaut',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 11,
        username: 'Odin',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 12,
        username: 'Cinder',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 13,
        username: 'Zubashi',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 14,
        username: 'Cogitabundus',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 15,
        username: 'choosetheforce',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 16,
        username: 'jumpyLion',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 17,
        username: 'TepG',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 18,
        username: 'KingKirb',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 19,
        username: 'BigBluePin',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 20,
        username: 'Beowulf',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 21,
        username: 'LoveYoSelfPlz',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 22,
        username: 'Skuzi',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 23,
        username: 'chase',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 24,
        username: 'Om1nous',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 25,
        username: 'God',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 26,
        username: 'ERmilburn02',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 27,
        username: 'daneharnett',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 28,
        username: 'FelixTFD',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 29,
        username: 'LeafyGreenBoi272',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 30,
        username: 'Saloman',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 31,
        username: 'DragonMaster13',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 32,
        username: 'DialMforMeow',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 33,
        username: 'Blossom',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 34,
        username: 'MacieG',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 35,
        username: 'karamac',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 36,
        username: 'Cullen',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 37,
        username: 'Simply_Jxded',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 38,
        username: 'Silverman830',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 39,
        username: 'Ely',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 40,
        username: 'sizzlorr',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 41,
        username: 'F-I-S-H-Y',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 42,
        username: 'Jaynerd',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 43,
        username: 'DarkKnight',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 44,
        username: 'git',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 45,
        username: 'Mint_Aldama',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 46,
        username: 'Ragchomp',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 47,
        username: 'Pongfee',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 48,
        username: 'hayjw916',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 49,
        username: 'horny_paladin',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 50,
        username: 'AutoTF',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 51,
        username: 'Amy',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 52,
        username: 'knap',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 53,
        username: 'Coty',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 54,
        username: 'alThesexyoverLord',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 55,
        username: 'Corukai',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 56,
        username: 'Mamo',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 57,
        username: 'Deadman',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 58,
        username: 'Kredge',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 59,
        username: 'RyanTFD',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 60,
        username: 'Peemard',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 61,
        username: 'iEnvyU',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 62,
        username: 'ponkotSuzu',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 63,
        username: 'JamesMMA',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 64,
        username: 'byFd',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 65,
        username: 'washi',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 66,
        username: 'hoby2000',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 67,
        username: 'Kiree',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 68,
        username: 'DanoToast',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 69,
        username: 'kylloren',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 70,
        username: 'ecoder',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 71,
        username: 'Connorses',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 72,
        username: 'enderthree',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 73,
        username: 'Lufia',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 74,
        username: 'heilsusafi',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 75,
        username: 'L-four',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 76,
        username: 'Elysian',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 77,
        username: 'Septimus',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 78,
        username: 'Swemmertje',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 79,
        username: 'miniboc',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 80,
        username: 'Carsair',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 81,
        username: 'soloc',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 82,
        username: 'GreatGameGal',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 83,
        username: 'Ewan',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 84,
        username: 'ColinTFD',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 85,
        username: 'Saylux',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 86,
        username: 'the_fat_kid_nick',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 87,
        username: 'Espeon',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 88,
        username: 'Pink_Chair',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 89,
        username: 'AHouse',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 90,
        username: 'BlackRoseTengu',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 91,
        username: 'dumpsterfirebrea2o',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 92,
        username: 'dyne',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 93,
        username: 'Hokagabe',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 94,
        username: 'Yellow',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 95,
        username: 'Scorpi',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 96,
        username: 'funniecheeseman',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 97,
        username: 'timefrog',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 98,
        username: 'tuxun',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 99,
        username: 'TheLastPogBender',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
    {
        place: 100,
        username: 'wasbinko',
        total_experience: 0,
        daily_experience: 0,
        weekly_experience: 0,
        monthly_experience: 0,
    },
]
